enum Stacks {
    FRONTEND = 'Frontend',
    BACKEND = 'Backend',
    FULLSTACK = 'Fullstack',
    MOBILE = 'Mobile',
    DEVOPS = 'DevOps',
    DATA_SCIENCE = 'Data Science',
    MACHINE_LEARNING = 'Machine Learning',
    GAME_DEVELOPMENT = 'Game Development',
    EMBEDDED_SYSTEMS = 'Embedded Systems',
    CLOUD_COMPUTING = 'Cloud Computing',
    CYBER_SECURITY = 'Cyber Security',
    BLOCKCHAIN = 'Blockchain',
    JAVA = 'Java',
    JAVASCRIPT = 'JavaScript',
    PYTHON = 'Python',
    CSHARP = 'C#',
    CPLUSPLUS = 'C++',
    RUBY = 'Ruby',
    SWIFT = 'Swift',
    KOTLIN = 'Kotlin',
    PHP = 'PHP',
    TYPESCRIPT = 'TypeScript',
    GO = 'Go',
    RUST = 'Rust',
    SCALA = 'Scala',
    HTML_CSS = 'HTML/CSS',
    REACT = 'React',
    ANGULAR = 'Angular',
    VUE = 'Vue',
    NODE_JS = 'Node.js',
    DJANGO = 'Django',
    FLASK = 'Flask',
    SPRING = 'Spring',
    LARAVEL = 'Laravel',
    DOTNET = '.NET',
    SQL = 'SQL',
    NO_SQL = 'No SQL',
    OTHERS = 'Others'
}

export default Stacks;